<?php 
require 'config.php'; 
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    csrf_verify();
    $pdo = getDB();
    $stmt = $pdo->prepare("SELECT * FROM users WHERE email = ?");
    $stmt->execute([$_POST['email']]);
    $user = $stmt->fetch();
    
    if ($user && password_verify($_POST['password'], $user['password_hash'])) {
        $_SESSION['user_id'] = $user['id'];
        $_SESSION['role'] = $user['role'];
        $_SESSION['full_name'] = $user['full_name'];
        $_SESSION['authority_id'] = $user['authority_id'] ?? null;
        header('Location: dashboard.php');
        exit;
    }
    $error = 'Invalid email or password';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login - Disaster System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
   
</head>
<body class="bg-light main-section" style="background-image: url('./images/4.webp'); background-repeat: no-repeat; background-size: cover;">
    <div class="container">
        <div class="row justify-content-center align-items-center min-vh-100">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow">
                    <div class="card-body p-4">
                        <h3 class="text-center mb-4">🚨 Disaster System</h3>
                        <?php if ($error): ?>
                            <div class="alert alert-danger"><?= $error ?></div>
                        <?php endif; ?>
                        <form method="POST">
                            <input type="hidden" name="csrf" value="<?= $_SESSION['csrf_token'] ?>">
                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" required autofocus>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>
                            <button class="btn btn-danger w-100 py-2">Login</button>
                        </form>
                        <div class="alert alert-light border mt-3 mb-0 small">
                            Authority accounts are generated by the admin dashboard and sign in here using the generated email and temporary password.
                        </div>
                        <div class="text-center mt-3">
                            <a href="register.php" class="text-decoration-none">New citizen? Register here</a>
                        </div>
                        <div class="text-center mt-2 small text-muted">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
